server:
  port: 9966
spring:
  liquibase:
    change-log: classpath:db/changelog.xml
    enabled: true
    drop-first: true
    default-schema: test
    liquibase-schema: test

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: test
    open-in-view: false